### ISSUE TITLE
Possible to use for Firefox Stable? 

### ISSUE THREAD

**Issue by emvaized** [CYFARE/HellFire#4]
Hi there 👋 
I'm using Firefox Stable v133.0, and would like to use compiler optimizations HellFire provides. I especially like that the installer will simply update my existing installation instead of installing a new version of the browser.

However, the installer is targeted for Nightly build, and I would prefer to keep my stable version. Could it be possible?

**Comment by CYFARE** [comment]
Hey there!
Sure, I'll start providing stable & esr releases as well.

**Comment by CYFARE** [comment]
Hi, I've put up a small contructive rant on Mozilla regarding a very consistent issue. In short, I'm providing hardened + sandbox enabled builds of Nightly (sort of stable part / tested branch) releases along with modern instruction sets - AVX2 + SSE4.2 now. This latest FP1 release, if it runs on your system, will give you massive performance and security improvements. Unfortunately, due to the mentioned issue in the rant part of release notes, release/stable branch can't be build unless Mozilla fixes up some stuff from their side.

New release: https://github.com/CYFARE/HellFire/releases/tag/v135.0a1_FP1

Closing this issue right now as 'wontfix' for now. Unless they fix the issue and then will hopefully plan accordingly.
